name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  http: ^1.2.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/complaints.json

  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-Thin.ttf
        - asset: fonts/Outfit-SemiBold.ttf
        - asset: fonts/Outfit-Black.ttf
        - asset: fonts/Outfit-Bold.ttf
        - asset: fonts/Outfit-ExtraBold.ttf
        - asset: fonts/Outfit-ExtraLight.ttf
        - asset: fonts/Outfit-Light.ttf
        - asset: fonts/Outfit-Medium.ttf
        - asset: fonts/Outfit-Regular.ttf










